- name: variable preferene
  hosts: frontend
  # vars:
  #   full_name: "nagu from play"
  # vars_files:
  # - course.yaml
  # vars_prompt:
  # - name: full_name
  #   prompt: "please enter your full_name"
  #   private: false
  tasks:
  - name: print vars preferene
    vars:
     # full_name: "nagu from TASK level"
    debug:
      msg: "HI, {{ full_name }}"


# 1.command args
# 2. task level
# 3. vars_files
# 4. prompt
# 5.play
# 6.inventory